# appveyor.yml
build: off

clone_folder: /root/go/src/github.com/$username/$project

environment:
  GOPATH: /root/go

stack: go 1.18

before_test:
  - go vet ./main.go
test_script:
  - go test ./main.go